CREATE DATABASE mvc;
USE mvc;

CREATE TABLE cidade(
	codibge INT NOT NULL,
	nome CHAR(70) NOT NULL,
	uf CHAR(50) NOT NULL,
	PRIMARY KEY(codibge)
);

INSERT INTO cidade (codibge, nome, uf) VALUES(1100015, 'Alta Floresta Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100023, 'Ariquemes', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100031, 'Cabixi', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100049, 'Cacoal', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100056, 'Cerejeiras', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100064, 'Colorado do Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100072, 'Corumbiara', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100080, 'Costa Marques', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100098, 'Espigão Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100106, 'Guajará-Mirim', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100114, 'Jaru', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100122, 'Ji-Paraná', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100130, 'Machadinho Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100148, 'Nova Brasilândia Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100155, 'Ouro Preto do Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100189, 'Pimenta Bueno', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100205, 'Porto Velho', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100254, 'Presidente Médici', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100262, 'Rio Crespo', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100288, 'Rolim de Moura', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100296, 'Santa Luzia Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100304, 'Vilhena', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100320, 'São Miguel do Guaporé', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100338, 'Nova Mamoré', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100346, 'Alvorada Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100379, 'Alto Alegre dos Parecis', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100403, 'Alto Paraíso', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100452, 'Buritis', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100502, 'Novo Horizonte do Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100601, 'Cacaulândia', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100700, 'Campo Novo de Rondônia', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100809, 'Candeias do Jamari', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100908, 'Castanheiras', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100924, 'Chupinguaia', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1100940, 'Cujubim', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101005, 'Governador Jorge Teixeira', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101104, 'Itapuã do Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101203, 'Ministro Andreazza', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101302, 'Mirante da Serra', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101401, 'Monte Negro', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101435, 'Nova União', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101450, 'Parecis', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101468, 'Pimenteiras do Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101476, 'Primavera de Rondônia', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101484, 'São Felipe Oeste', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101492, 'São Francisco do Guaporé', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101500, 'Seringueiras', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101559, 'Teixeirópolis', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101609, 'Theobroma', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101708, 'Urupá', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101757, 'Vale do Anari', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1101807, 'Vale do Paraíso', 'Rondônia');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200013, 'Acrelândia', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200054, 'Assis Brasil', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200104, 'Brasiléia', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200138, 'Bujari', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200179, 'Capixaba', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200203, 'Cruzeiro do Sul', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200252, 'Epitaciolândia', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200302, 'Feijó', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200328, 'Jordão', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200336, 'Mâncio Lima', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200344, 'Manoel Urbano', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200351, 'Marechal Thaumaturgo', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200385, 'Plácido de Castro', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200393, 'Porto Walter', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200401, 'Rio Branco', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200427, 'Rodrigues Alves', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200435, 'Santa Rosa do Purus', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200450, 'Senador Guiomard', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200500, 'Sena Madureira', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200609, 'Tarauacá', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200708, 'Xapuri', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1200807, 'Porto Acre', 'Acre');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300029, 'Alvarães', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300060, 'Amaturá', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300086, 'Anamã', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300102, 'Anori', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300144, 'Apuí', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300201, 'Atalaia do Norte', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300300, 'Autazes', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300409, 'Barcelos', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300508, 'Barreirinha', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300607, 'Benjamin Constant', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300631, 'Beruri', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300680, 'Boa Vista do Ramos', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300706, 'Boca do Acre', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300805, 'Borba', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300839, 'Caapiranga', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1300904, 'Canutama', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301001, 'Carauari', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301100, 'Careiro', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301159, 'Careiro da Várzea', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301209, 'Coari', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301308, 'Codajás', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301407, 'Eirunepé', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301506, 'Envira', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301605, 'Fonte Boa', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301654, 'Guajará', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301704, 'Humaitá', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301803, 'Ipixuna', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301852, 'Iranduba', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301902, 'Itacoatiara', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1301951, 'Itamarati', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302009, 'Itapiranga', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302108, 'Japurá', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302207, 'Juruá', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302306, 'Jutaí', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302405, 'Lábrea', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302504, 'Manacapuru', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302553, 'Manaquiri', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302603, 'Manaus', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302702, 'Manicoré', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302801, 'Maraã', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1302900, 'Maués', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303007, 'Nhamundá', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303106, 'Nova Olinda do Norte', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303205, 'Novo Airão', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303304, 'Novo Aripuanã', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303403, 'Parintins', 'Amazonas');
INSERT INTO cidade (codibge, nome, uf) VALUES(1303502, 'Pauini', 'Amazonas');